@startuml Backup-HPV(1-2 part)

title Backup-HPV(1-2 part)
!theme sunlust

start

:Set up command line switches;
:Set variable for Hyper-V host name;
:Get script directory path;

if (backup-hpv.ini exists) then (yes)
  :Get configuration from backup-hpv.ini;
else (no)
endif

:Set LogPath;
:Initialize error count and job description;
:Set SMTP server details;
:Set email details;

:Get short date format;
:Create Registry key;

while (For each VM to backup)
  :Start-Copy_Daten function;
  if (Source directory exists) then (yes)
    if (Source is folder) then (yes)
      :Get child folders;
      :Get existing dest file names;
      :Get small source files;
      if (Small source files exist) then (yes)
        :Log small source file errors;
      endif
      :Get files to copy;
      if (Files to copy exist) then (yes)
        :Copy each file;
        if (Source and dest file sizes match) then (yes)
          :Log successful copy;
        else (no)
          :Log copy error;
          :Increment error count;
        endif
      endif
    else (no)
      :Copy file;
    endif
  else (no)
    :Log source directory error;
    :Increment error count;
  endif
  if (Copy was successful) then (yes)
    :Compress backup;
  else (no)
  endif
endwhile

if (Errors occurred) then (yes)
  :Set email subject with error;
else (no)
  :Set email subject without error;
endif

:Send email log;

stop
@enduml
